### ISSUE TITLE
Low Precision of FaceDetection model when used without FaceMesh

### ISSUE THREAD

**Issue by alexandernst** [vladmandic/human#330]
Is there a way to get (or convert?) Mediapipe's FaceDetect model, the one with the 6 landmarks? ( https://codepen.io/mediapipe/full/dyOzvZM )

I'm currently using this model and the information it provides is more than enough for my needs.

**Comment by vladmandic** [comment]
sorry this took a while, but i was busy with another project. anyhow, i've just pushed a major update on github that reimplements landmarks for blazeface.

- blazeface scaling math was wrong (most visible on left/right ear, but that's just the symptom)
- blazeface annotations were not part of interpolation (so `human.next` did nothing for them, thus results were jumpy)
- blazeface annotations were not drawn in `human.draw` methods if mesh was disabled

yes, blazeface is far from perfect as its supposed to be a lightweight face detector only before face is processed in mesh module and then blazeface results are pretty much discarded/replaced, but this makes blazeface at least viable if mesh is disabled.

**Comment by alexandernst** [comment]
Great news!! Let me test this and I'll report back :)

**Comment by vladmandic** [comment]
i'm closing this issue for now, so this part of the code can be marked as resolved.  
i'm open to include any additional suggestions, so feel free to either continue on this thread or open a new issue.

**Comment by alexandernst** [comment]
Hi! I tested this, but unfortunately it's still not fixed. See attachment:

![image](https://user-images.githubusercontent.com/89727/216793314-34aeb79c-f8c7-421d-8d0f-94912e55dff0.png)

Landmarks aren't "jumping" anymore, but they are way off of the position they should be at.

**Comment by vladmandic** [comment]
hmm, i'll re-check new scaling. at least the other stuff seems to be working.  
based on your example, seems there is an incorrect offset to +up+right, but general scale is ok.

**Comment by alexandernst** [comment]
Actually, "+up+right" doesn't seem to be altways the case. Try moving around and you'll see that the points offset error varies.

Examples:

![image](https://user-images.githubusercontent.com/89727/216793829-e7d1c04d-8658-4978-8283-34486ff18fae.png)

![image](https://user-images.githubusercontent.com/89727/216793854-5e291019-d4c4-4e6b-82b0-902f65bbf71f.png)

**Comment by vladmandic** [comment]
I'll test it in the next few days. Pretty sure it's going to be annoying to nail down and then the fix will be one line.

**Comment by vladmandic** [comment]
updated, can you try?

**Comment by alexandernst** [comment]
Hi! I just tested it. The new demo seems to be working as expected :)

One final question, though. Is there a way I can get the left/right face edge, instead of the left/right ear landmarks?

**Comment by vladmandic** [comment]
> Hi! I just tested it. The new demo seems to be working as expected :)

Good! Closing the issue as resolved, but feel free to keep posting on this thread.

> Is there a way I can get the left/right face edge, instead of the left/right ear landmarks?

Closest I can think of would be to expose `blazeface` decoded box results before post-processing:
<https://github.com/vladmandic/human/blob/1bf65413fe5d3a437ea80247647b5e5510816aab/src/face/blazeface.ts#L101>

But it would have to be surfaced in higher level modules as well to be user consumable. Not sure if I want to have another dataset exposed without strong use-case - what would that be?

**Comment by alexandernst** [comment]
Hi @vladmandic ! I'm sorry for respawning this once again, but I'm detecting performance issues (maybe in the model itself?).

Here is a comparison between your implementation of blazeface and mediapipe's demo. Check how the tracking of the landmarks is much slower in blazeface.


https://user-images.githubusercontent.com/89727/222159232-8ded2d6c-6d47-4e6e-975e-40526c650e18.mp4

-

And here is a recording of the facemesh demo, which is running smoothly as expected:


https://user-images.githubusercontent.com/89727/222159890-5d9fc89a-9900-404c-b418-b949bd718aa7.mp4

-

Can you confirm if this is an issue with the model itself or with the implementation?

**Comment by vladmandic** [comment]
i'm not seeing any major performance issues on my system, blazeface runs at constant 30fps.
one difference in behavior if facemesh is disabled, the face caching gets disabled as well as there is insufficient data to make assumptions - so blazeface runs on each frame instead of being skipped.
and *slow* tracking comes from interpolation - but it should still track much faster.

if you set `config.async = false` (default is async execution and then performance stats are bundled for all models), you can dump `result.performance` object to gather some stats - can you share them (with mesh enabled and disabled).
